const ja = {
  translation: {
    // define translations below
    form: {
      required: 'この項目は必須です。',
      email: 'メール形式が無効です。',
      password: {
        minLength: 'パスワードは8文字以上である必要があります。',
        confirm: 'パスワードの確認が一致しません。',
        strong:
          'パスワードには、大文字1文字、特殊文字1文字、および少なくとも8文字が含まれている必要があります。',
      },
    },
    labels: {
      first_name: 'ファーストネーム',
      last_name: '苗字',
      login: 'ログイン',
      signup: 'サインアップ',
      remember_me: '私を覚えてますか',
      forgot_password: 'パスワードをお忘れですか？',
      email_address: '電子メールアドレス',
      password: 'パスワード',
      confirm_password: 'パスワードを認証する',
      submit: '送信',
      update: 'アップデート',
      save: '保存する',
      add_new: '新しく追加する',
      reset_password: 'パスワードを再設定する',
      new_password: '新しいパスワード',
      confirm_new_password: '新しいパスワードを確認',
      enter_keyword: 'キーワードを入力してください',
      get_started: 'はじめましょう',
      integrations: '統合',
      settings: '設定',
      documentation: 'ドキュメンテーション',
      fullname: 'フルネーム',
      inquiry_content: 'お問合わせ内容',
      navigation: 'ナビゲーション',
      resources: 'リソース',
      cancel: 'キャンセル',
      action: 'アクション',
      showPassword: 'パスワードを表示',
      hidePassword: 'パスワードを隠す',
      role: '役割',
      notifications: '通知',
      noNotifications: '新しい通知はありません。',
      newNotification: '新しい通知があります。',
    },
    pages: {
      login: {
        no_account: 'アカウントをお持ちですか？',
        sign_up_here: 'ここでサインアップ',
      },
      signup: {
        agree_to_terms: '[サインアップ]をクリックすると、読んだことに同意したことになります',
        signup_complete:
          '確認メールが受信トレイに送信されました。 リンクをクリックして、登録プロセスを完了します。',
        terms_conditions: '規約と条件',
        create_free_account: '無料アカウントを作成する',
        signup_description: '匿名でフィードバックを共有する従業員が数千人います',
        already_have_account: 'アカウントをお持ちですか？',
        sign_in_here: 'ここでサインイン',
      },
      forgot_password: {
        sub_heading: 'アカウントを復旧するには、以下にメールアドレスを入力してください。',
        success: 'パスワードをリセットする方法については、受信トレイを確認してください。',
      },
      reset_password: {
        sub_heading: '新しいパスワードを入力してください。',
        success: 'パスワードは正常に更新されました。',
      },
      users: {
        user_created: 'ユーザーが作成されました。',
        user_updated: 'ユーザーの詳細が更新されました。',
        user_deleted: 'ユーザーが削除されました',
        add_user: 'ユーザーを追加する',
        edit_user: 'ユーザー編集',
        delete_user: 'ユーザーを削除',
        first_name: 'ファーストネーム',
        last_name: '苗字',
        email_address: '電子メールアドレス',
        status: '状態',
        role: '役割',
        delete_confirmation: '選択したユーザーを削除してもよろしいですか？',
      },
      activate: {
        heading: 'アカウントをアクティブ化',
        subtitle: 'アカウントをアクティブ化するためのパスワードを設定します。',
        activated: 'アカウントが有効になりました。 これで、アカウントにログインできます。',
      },
      dashboard: {
        main_heading: '匿名従業員フィードバック！',
        sub_heading: 'Reactプロジェクトの開発に関する軽量の定型文。',
        new_users: '新しいユーザー',
        total_sales: '総売上高',
        total_orders: '総注文数',
      },
      not_found: {
        title: 'ページが見つかりません',
        sub_heading: 'お探しのページは削除されたか、別の場所へ移動した可能性があります。',
        back_to_top: 'トップページへ戻る',
      },
      faq: {
        heading: 'よくあるご質問',
        sub_heading: 'お客様からお問い合わせいただく質問をQ&A形式でまとめました。',
      },
      inquiry: {
        heading: 'お問い合わせ',
        sub_heading: 'このままお問い合わせされる方は下記のフォームにご入力ください。',
        success_message: 'お問い合わせを送信しました。',
        failed_message: '送信中にエラーが発生しました。',
      },
      profile: {
        heading: 'プロファイル編集',
        sub_heading: 'アカウント情報を更新します。',
        success_message: '詳細が正常に更新されました。',
        failed_message: '更新に失敗しました。',
      },
      landing: {
        main_heading: '匿名従業員フィードバック！',
        sub_heading:
          'すべての声が大切とされるオープンなコミュニケーション文化を築きましょう。安全かつ匿名でフィードバックを共有できます。',
        why_heading: 'なぜ匿名を選ぶのですか？',
        docker: {
          heading: '完全な匿名性',
          description:
            'あなたのアイデンティティは保護されています。 報復や判断の恐れなしにフィードバックを共有できます。',
        },
        react: {
          heading: 'リアルタイムフィードバック',
          description:
            'フィードバックを即座に投稿し、応答します。 意味のある職場の会話を作成します。',
        },
        laravel: {
          heading: '実行可能な洞察',
          description: '匿名フィードバックを実行可能な改善に変えます。',
        },
        our_customers_heading: 'お客様',
        reviews_heading: '私たちのクライアントが言うこと',
        see_all_reviews: 'すべてのレビューを見る',
        call_to_action: '職場を変える準備はできていますか？',
        call_to_action_description:
          '匿名フィードバックを通じて、より良い職場文化を築く組織が増えています。',
        call_to_action_button: '今すぐ無料で始める',
      },
      about: {
        main_heading: '私たちの物語',
        sub_heading:
          '私たちは、私たちが信じる人々のために誇りに思う作品をデザイン、作成、制作するために協力しています。',
        meet_the_team: 'チームに会う',
        team_description:
          '思いやり、独創性、細部へのこだわりは、私たちが設計、製造、販売するすべての製品の基盤です。',
        our_mission: '私たちの使命',
        mission_description:
          '私たちの使命は、ビジネスのトレンドと人々中心の文化と行動を重視する提案を重視する高品質のサービスと製品で、卓越したテクノロジーを広めることです。',
        our_activities: '私たちの活動',
        activities_description: '生計を立てるのに忙しくて、生計を立てることを忘れないでください。',
      },
      roles: {
        role_created: 'ロールが作成されました。',
        role_updated: '役割の詳細が更新されました。',
        role_deleted: '役割が削除されました。',
        add_role: '役割の追加',
        edit_role: '役割の編集',
        delete_role: '役割の削除',
        name: '名前',
        permissions: '許可',
        delete_confirmation: '選択した役割を削除してもよろしいですか?',
      },
      unauthorized: {
        main_heading: '許可されていません。',
        sub_heading: '申し訳ありませんが、このリソースにアクセスする権限がありません。',
      },
    },
    menu: {
      home: '家',
      about: '約',
      inquiry: 'お問い合わせ',
      faq: 'よくあるご質問',
      dashboard: 'ダッシュボード',
      users: 'ユーザー',
      orders: '注文',
      reports: 'レポート',
      integrations: '統合',
      profile: 'プロフィール',
      login: 'ログイン',
      logout: 'ログアウト',
      terms: '利用規約',
      privacy_policy: 'プライバシーポリシー',
      documentation: 'ドキュメンテーション',
      api_reference: 'APIリファレンス',
      support: 'サポート',
      styleguide: 'スタイルガイド',
      roles: '役割',
      broadcast: '放送',
      'create-post': '投稿を作成',
      'my-posts': 'マイ投稿',
      notifications: '通知',
      'my-upvotes': 'マイアップボート',
      settings: '設定',
    },
    sidebar: {
      employee: '従業員サイドバー',
    },
    table: {
      no_data: 'データなし。',
    },

    // ANON
    sidebarANON: {
      title: 'クイックアクション',
      new_feedback: 'ダッシュボード',
      chats: 'コンバージョン',
    },
    rightbarANON: {
      trending: 'トレンディングトピック',
      recent: '最近の活動',
      Flagged: 'フラグ付け',
      Commented: 'コメント',
      HRReply: 'HRリプライ',
      trendingLoading: 'トレンディングトピックを読み込んでいます...',
      trendingError: 'トレンディングトピックの読み込みに失敗しました',
      trendingNoData: 'トレンディングトピックがありません',
      recentLoading: '最近の活動を読み込んでいます...',
      recentError: '最近の活動の読み込みに失敗しました',
      recentNoData: '最近の活動がありません',
      PostedAt: '投稿者 :',
    },
    FeedANON: {
      title: '匿名フィードバックを共有',
      post: 'フィードバックを投稿',
      search: '投稿を検索...',
      category: 'カテゴリ',
      sort: '並び替え',
      allCategories: 'すべてのカテゴリ',
    },
    PostANON: {
      title: 'フィードバックを投稿',
      body: 'あなたの思いは何ですか？ あなたのフィードバックは完全に匿名です...',
      category: 'カテゴリ',
      content: 'コンテンツ',
      titlePost: 'タイトル',
      sort: '並び替え',
      newest: '新しい順',
      oldest: '古い順',
      loadingPosts: '投稿を読み込んでいます...',
      noPostsFound: '投稿がありません',
      edit: '編集',
      delete: '削除',
      editingPost: '投稿を編集中',
      currentAttachments: '現在の添付ファイル',
      cancelRemove: '削除をキャンセル',
      removeAttachment: '添付ファイルを削除',
      addNewFiles: '新しいファイルを追加',
      cancel: 'キャンセル',
      saving: '保存中...',
      save: '保存',
      upvote: 'アップボート',
      comments: 'コメント',
      chat: 'チャット',
      addComment: 'コメントを追加...',
      postComment: 'コメントを投稿',
      loadingComments: 'コメントを読み込んでいます...',
      noComments: 'コメントがありません。 最初のコメントを投稿してください！',
      cancelReply: 'リプライをキャンセル',
      reply: 'リプライ',
      writeReply: 'リプライを書く...',
      postReply: 'リプライを投稿',
      deletePost: '投稿を削除',
      messageDeletePost:
        '選択した投稿を削除してもよろしいですか？ この操作は元に戻すことができません。',
      defaultDeleteTitle: '削除確認',
      defaultDeleteMessage:
        '選択した項目を削除してもよろしいですか？ この操作は元に戻すことができません。',
      defaultDeleteConfirmText: '削除',
      defaultDeleteCancelText: 'キャンセル',
      loadingDeleting: '削除中...',
      postResolved: 'この投稿は解決されました',
      commentsDisabled: '解決された投稿のコメントは無効です',
      dropFilesHere: 'ファイルをここにドロップしてください！',
      dragAndDropFilesHere: 'ファイルをドラッグ&ドロップしてください',
      orClickToBrowseFiles: 'またはファイルを選択してください',
      supportedFormats: 'サポートされるフォーマット:',
      maxFileSize: '最大ファイルサイズ:',
      attachedFiles: '添付ファイル',
    },
    FlaggedPostsANON: {
      title: 'フラグ付けされた投稿',
      No: 'No.',
      postTitle: '投稿タイトル',
      flaggedBy: 'フラグ付け者',
      reason: '理由',
      status: '状態',
      flaggedAt: 'フラグ付け日時',
      escalatedAt: 'スケールアップ日時',
      open: 'オープン',
      inReview: 'レビュー中',
      escalated: 'スケールアップ',
      resolved: '解決',
    },
    ChatsANON: {
      title: 'コンバージョン',
      viewPosts: '投稿を表示',
      selectConversation: 'コンバージョンを選択',
      chooseConversation: 'コンバージョンを選択してください',
      noMessages: 'メッセージがありません。 コンバージョンを開始してください！',
      noConversation: 'コンバージョンを選択',
      noConversationSelected: 'コンバージョンが選択されていません',
      noConversationSelectedButton: '投稿を表示',
      noActiveChats: 'コンバージョンがありません。',
      noChats:
        'コンバージョンがありません。 投稿に&quot;チャット&quot;をクリックしてコンバージョンを開始してください。',
      failedToLoadChats: 'コンバージョンの読み込みに失敗しました',
      noActivity: '活動なし',
      unknownUser: '不明なユーザー',
      unknownPost: '不明な投稿',
      chattingAboutFeedback: 'フィードバックについてチャットしています',
      placeholder: 'メッセージを入力してください...',
      placeholderSending: '送信中...',
      placeholderSend: '送信',
      browsePosts: '投稿を表示',
    },
  },
};

export default ja;
